---
abstract: 'install files to system folders according to FHS (or Sys::Path settings)'
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
build_requires:
  File::Temp: 0
  Test::Compile: 0.08
  Test::Dirs: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
keywords:
  - system
  - paths
  - instalation
  - deployment
  - applications
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Build-SysPath
provides:
  Module::Build::SysPath:
    file: lib/Module/Build/SysPath.pm
    version: 0.14_01
requires:
  Digest::MD5: 0
  File::Basename: 0
  File::Path: 2.07
  File::Spec: 0
  List::MoreUtils: 0
  Sys::Path: 0.11
  Text::Diff: 0
resources:
  bugtracker: http://github.com/jozef/Module-Build-SysPath/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jozef/Module-Build-SysPath.git
version: 0.14_01
